FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

# Установка зависимостей
RUN python -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["/opt/venv/bin/python", "main1.py"] 