FROM python:3.9-slim

WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt .

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы
COPY . .

# Указываем команду для запуска
CMD ["python", "main1.py"] 